[package]
name = "rust-graphql-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
async-graphql = "5.0.4"
async-graphql-actix-web = "5.0.4"
lazy_static = "1.4.0"